# WebSSH服务配置
server:
  address: ":8080"

# Kubernetes配置
k8s:
  config_path: ""  # 留空将使用集群内配置

# 认证配置
auth:
  verify_token_url: ""  # 验证token的URL，留空将禁用认证
  timeout: 5           # 超时时间（秒）

# 长文本处理配置
paste:
  max_chunk_size: 512          # 每次写入的最大字节数（减小以提高稳定性）
  write_delay_ms: 20           # 写入间隔（毫秒）（增加以避免缓冲区溢出）
  confirm_threshold: 512       # 超过此大小的文本需要用户确认（减小阈值）
  max_paste_size: 1048576      # 最大允许粘贴大小（1MB）
  enable_confirmation: true    # 是否启用粘贴确认
  use_bracket_paste: true      # 是否使用括号粘贴模式（推荐）
  clean_control_chars: true    # 是否清理控制字符
  multiline_threshold: 2       # 多行文本的行数阈值
