# WebSSH服务配置
server:
  address: ":8080"

# Kubernetes配置
k8s:
  config_path: ""  # 留空将使用集群内配置

# 认证配置
auth:
  verify_token_url: ""  # 验证token的URL，留空将禁用认证
  timeout: 5           # 超时时间（秒）

# 长文本处理配置
paste:
  max_chunk_size: 1024        # 每次写入的最大字节数
  write_delay_ms: 10          # 写入间隔（毫秒）
  confirm_threshold: 1024     # 超过此大小的文本需要用户确认
  max_paste_size: 1048576     # 最大允许粘贴大小（1MB）
  enable_confirmation: true   # 是否启用粘贴确认
